adjective1 = input('Type an adjective: ')
animal = input('animal: ')
verb1 = input('verb1: ')
exclamation = input("exclamation: ")
verb2 = input('verb2: ')
verb3 = input('verb3: ')
#print(f'hello Sadiq  {plural}')
#print(verb)
#print(adjective)
#print(noun)
print(f'The other day, I was really in trouble. it all started when i saw a very {adjective1}, {animal}, {verb1} down the hallway. {exclamation}. I yelled. But all i could think to do was to {verb2}, over and over. Miraculously, that caused it to stop, but not before it tried to {verb3} right i front of my family.')
#print(f'')